project:
  type: website
  output-dir: build
  resources:
    - reports/conflicts_eda.html

lang: en
language:
  section-title-appendices: "Appendix"

website:
  title: "Geopoliitcal Colflic & Trade Explorer"
  search: true
  sidebar:
    style: "floating"
    search: true
    contents:
      - index.qmd
      - data_report.qmd
      - viz_design_report.qmd
      - evaluation.qmd
      - meeting_notes.qmd
      - project_charta.qmd

format:
  html:
    theme: cosmo
    sass-cache: false
    css: styles.css
    toc: true
    page-layout: full
      

number-sections: true

bibliography: refs.bib
csl: vancouver-brackets.csl

jupyter: python3

execute:
  freeze: auto

editor:
  render-on-save: true